"use client";
import { useState } from "react";

const types = [["Call","phone"],["Meeting","users"],["Email","mail"],["Task","check"],["Deadline","calendar"],["Lunch","briefcase"],["Note","note"]];
const weekdays = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const input = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none placeholder:text-slate-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
function Icon({name,size=18,className=""}){const p={phone:<path d="M8 3H5a2 2 0 0 0-2 2c0 9 7 16 16 16a2 2 0 0 0 2-2v-3l-4-1-1 2a12 12 0 0 1-9-9l2-1Z"/>,users:<><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 6a3 3 0 0 1 0 6M16 14a5 5 0 0 1 5 5"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></>,check:<path d="m5 12 4 4L19 6"/>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/></>,briefcase:<><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V4h6v3M3 12h18"/></>,note:<><path d="M5 3h14v14l-4 4H5z"/><path d="M15 21v-4h4M8 8h8M8 12h6"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,left:<path d="m15 18-6-6 6-6"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className}>{p[name]}</svg>}
const date=(iso)=>{const [y,m,d]=iso.split("-").map(Number);return new Date(y,m-1,d)};
const iso=(d)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const shift=(value,n)=>{const d=date(value);d.setDate(d.getDate()+n);return iso(d)};
const mins=(t)=>{const [h,m]=t.split(":").map(Number);return h*60+m};
const clock=(t)=>{const [h,m]=t.split(":").map(Number);return `${h%12||12}:${String(m).padStart(2,"0")} ${h>=12?"PM":"AM"}`};
function days(value){const d=date(value),y=d.getFullYear(),m=d.getMonth(),a=Array((new Date(y,m,1).getDay()+6)%7).fill(null);for(let n=1;n<=new Date(y,m+1,0).getDate();n++)a.push(iso(new Date(y,m,n)));while(a.length%7)a.push(null);return a}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>}

export default function ActivitySchedulerModal({deal,activities=[],onClose,onSave}){
 const [form,setForm]=useState({title:`Call with ${deal.contact||deal.organization}`,type:"Call",date:iso(new Date()),start:"10:00",end:"10:30",priority:"Normal",reminder:"30 minutes before",location:"",videoLink:"",assignedTo:deal.assignedTo||"Unassigned",participants:deal.contact||"",description:"",markAsNext:true});
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 const hours=Array.from({length:13},(_,i)=>i+8), height=58;
 const current=activities.filter(a=>a.scheduledDate===form.date&&a.startTime&&a.status!=="done");
 const startTop=Math.max(0,(mins(form.start)-480)/60*height), eventHeight=Math.max(34,(Math.max(mins(form.end),mins(form.start)+30)-mins(form.start))/60*height);
 const chooseHour=h=>setForm(v=>({...v,start:`${String(h).padStart(2,"0")}:00`,end:`${String(Math.min(h+1,23)).padStart(2,"0")}:00`}));
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/40 p-3 backdrop-blur-[2px]" onMouseDown={onClose}>
  <section role="dialog" aria-modal="true" className="flex max-h-[94vh] w-full max-w-[1180px] flex-col overflow-hidden rounded-2xl border border-white/70 bg-white shadow-2xl" onMouseDown={e=>e.stopPropagation()}>
   <header className="flex items-center justify-between border-b border-slate-200 px-6 py-4"><div><h2 className="text-lg font-bold text-slate-950">Schedule an activity</h2><p className="mt-1 text-sm text-slate-500">Plan the next client action and check the team calendar before saving.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Close"><Icon name="close"/></button></header>
   <div className="grid min-h-0 flex-1 overflow-y-auto lg:grid-cols-[minmax(0,1.15fr)_minmax(380px,.85fr)] lg:overflow-hidden">
    <div className="space-y-5 overflow-y-auto p-6">
     <Field label="Activity title"><input autoFocus value={form.title} onChange={e=>set("title",e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-lg font-semibold outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100"/></Field>
     <div><p className="mb-2 text-xs font-semibold text-slate-600">Activity type</p><div className="grid grid-cols-4 gap-2 sm:grid-cols-7">{types.map(([type,icon])=><button type="button" key={type} onClick={()=>set("type",type)} className={`flex min-h-[68px] flex-col items-center justify-center gap-1.5 rounded-xl border px-2 text-[11px] font-semibold ${form.type===type?"border-blue-500 bg-blue-50 text-blue-700 shadow-sm":"border-slate-200 text-slate-500 hover:bg-blue-50"}`}><Icon name={icon}/>{type}</button>)}</div></div>
     <div className="grid gap-4 sm:grid-cols-[1.1fr_.75fr_.75fr]"><Field label="Date"><input type="date" value={form.date} onChange={e=>set("date",e.target.value)} className={input}/></Field><Field label="Starts"><input type="time" value={form.start} onChange={e=>set("start",e.target.value)} className={input}/></Field><Field label="Ends"><input type="time" value={form.end} onChange={e=>set("end",e.target.value)} className={input}/></Field></div>
     <div className="grid gap-4 sm:grid-cols-2">
      <Field label="Priority"><select value={form.priority} onChange={e=>set("priority",e.target.value)} className={input}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></Field>
      <Field label="Reminder"><select value={form.reminder} onChange={e=>set("reminder",e.target.value)} className={input}><option>At activity time</option><option>10 minutes before</option><option>30 minutes before</option><option>1 hour before</option><option>1 day before</option></select></Field>
      <Field label="Location"><input value={form.location} onChange={e=>set("location",e.target.value)} placeholder="Office, client site or address" className={input}/></Field>
      <Field label="Video meeting link"><input value={form.videoLink} onChange={e=>set("videoLink",e.target.value)} placeholder="Paste Google Meet or Zoom link" className={input}/></Field>
      <Field label="Assigned to"><select value={form.assignedTo} onChange={e=>set("assignedTo",e.target.value)} className={input}>{[deal.assignedTo||"Unassigned","Priya Sharma","Arjun Mehta","Kavya Singh"].filter((v,i,a)=>a.indexOf(v)===i).map(v=><option key={v}>{v}</option>)}</select></Field>
      <Field label="Participants"><input value={form.participants} onChange={e=>set("participants",e.target.value)} placeholder={`${deal.contact}, team members`} className={input}/></Field>
     </div>
     <Field label="Description or agenda"><textarea rows="4" value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Add the objective, agenda, preparation notes or expected outcome..." className={`${input} resize-y leading-6`}/></Field>
     <label className="flex cursor-pointer gap-3 rounded-xl border border-blue-100 bg-blue-50/60 p-4"><input type="checkbox" checked={form.markAsNext} onChange={e=>set("markAsNext",e.target.checked)} className="mt-0.5 h-4 w-4"/><span><b className="block text-sm text-slate-800">Set as next activity</b><span className="mt-1 block text-xs text-slate-500">Show this activity as the primary next action on the deal overview.</span></span></label>
    </div>
    <aside className="border-t border-slate-200 bg-slate-50/70 lg:overflow-y-auto lg:border-l lg:border-t-0">
     <div className="border-b border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><button type="button" onClick={()=>set("date",shift(form.date,-1))} className="rounded-lg border border-slate-200 p-2 text-slate-500"><Icon name="left"/></button><div className="text-center"><b className="text-sm text-slate-900">{date(form.date).toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</b><p className="mt-0.5 text-xs text-slate-500">{date(form.date).toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</p></div><button type="button" onClick={()=>set("date",shift(form.date,1))} className="rounded-lg border border-slate-200 p-2 text-slate-500"><Icon name="left" className="rotate-180"/></button></div><div className="grid grid-cols-7 gap-1 text-center">{weekdays.map(v=><b key={v} className="py-1 text-[10px] uppercase text-slate-400">{v}</b>)}{days(form.date).map((v,i)=>v?<button type="button" key={v} onClick={()=>set("date",v)} className={`relative h-8 rounded-lg text-xs font-semibold ${v===form.date?"bg-blue-600 text-white":"text-slate-600 hover:bg-blue-50"}`}>{date(v).getDate()}{activities.some(a=>a.scheduledDate===v&&a.status!=="done")&&<i className="absolute bottom-1 left-1/2 h-1 w-1 rounded-full bg-blue-400"/>}</button>:<span key={i}/>)}</div></div>
     <div className="p-5"><div className="mb-4 flex justify-between"><div><h3 className="text-sm font-bold">Day schedule</h3><p className="mt-1 text-xs text-slate-500">Click an hour to move the activity.</p></div><span className="h-fit rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold">{current.length} scheduled</span></div><div className="relative overflow-hidden rounded-xl border border-slate-200 bg-white" style={{height:hours.length*height}}>{hours.map((h,i)=><button type="button" key={h} onClick={()=>chooseHour(h)} className="absolute inset-x-0 border-t border-slate-100 text-left hover:bg-blue-50/30" style={{top:i*height,height}}><span className="absolute left-2 top-1.5 text-[10px] text-slate-400">{clock(`${String(h).padStart(2,"0")}:00`)}</span></button>)}<div className="absolute bottom-0 left-16 top-0 w-px bg-slate-100"/>{current.map(a=><div key={a.id} className="absolute left-[72px] right-3 rounded-lg bg-slate-200 px-2 py-1 text-[11px]" style={{top:Math.max(0,(mins(a.startTime)-480)/60*height)}}>{a.title}</div>)}<div className="absolute left-[72px] right-3 z-20 overflow-hidden rounded-lg border border-blue-500 bg-blue-600 px-3 py-2 text-white shadow-lg" style={{top:startTop,height:eventHeight}}><b className="flex items-center gap-2 text-xs"><Icon name={types.find(v=>v[0]===form.type)?.[1]} size={13}/>{form.title||form.type}</b><p className="mt-1 text-[10px] text-blue-100">{clock(form.start)} – {clock(form.end)}</p></div></div></div>
    </aside>
   </div>
   <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-6 py-4"><span className="flex items-center gap-2 text-xs text-slate-500"><Icon name="calendar" size={15} className="text-blue-600"/>{date(form.date).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}, {clock(form.start)} – {clock(form.end)}</span><div className="flex gap-2"><button type="button" onClick={onClose} className="rounded-lg px-3.5 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Cancel</button><button type="button" disabled={!form.title.trim()} onClick={()=>onSave(form)} className="flex items-center gap-2 rounded-lg bg-blue-600 px-3.5 py-2 text-sm font-semibold text-white shadow-sm disabled:opacity-50"><Icon name="calendar" size={16}/>Schedule activity</button></div></footer>
  </section>
 </div>
}
